### PR TITLE
Normative: Make FinalizationRegistry#cleanupSome normative optional

### PR DESCRIPTION
**Pull request by syg**
This reached consensus in the April 2020 TC39.

Do folks think additional verbiage is required here?

### CODE REVIEW

**Comment by erights** [comment]
> Do folks think additional verbiage is required here?

Are the terms in that verbiage explained elsewhere in the spec?

**Comment by syg** [comment]
It's used verbatim in Annex B but not defined up front AFAICT. I plan to discuss it at the next editor call.

**Comment by syg** [comment]
At the editor call, the decision was that we would stick with the phrasing `normative but optional`. On a case-by-case basis, if a particular normative optional feature is additionally constrained by upstream specifications, we would link directly to those upstream specifications in a non-normative note.

**Comment by littledan** [comment]
In addition to considering unifying the phrasing with Annex B, I want to suggest that you consider unifying it with ECMA-402's use of normative optional. I think we can continue to iterate on wording as this specification moves towards Stage 4, though, so I'll merge this PR as is.

**Comment by littledan** [comment]
Looking at the rendered spec, it's not very clear whether being "normative optional" groups with cleanupSome or unregister... We should probably iterate on this.

image

**Pull request merged**
