### PR TITLE
Clarify early finalization example

### PR DESCRIPTION
**Pull request by wingo**
See #98.

### CODE REVIEW

**Comment by wingo** [comment]
Not sure what you mean by "turns Stu", can you clarify?

I think though you are talking about similarities between this and the weakref+turns example that I agree is superfluous.  In that case IMHO early finalization in the form of finalizers running in turn where the user is still using components of the finalized object is significantly different from the keepalive mechanism from weakref.  I don't think early finalization errors are going to be common but I think not talking about early finalization runs the risk of constraining implementations to have a more restricted notion of visibility and liveness.

Consider, a new browser can come out with more optimizations, making a value that was previously live to be considered collectable, and provokes an early finalization bug in a user's code -- will "don't break the web" mean that that engine will have to roll back the optimization?  I am a little worried here that if we don't mention early finalization, we are unintentionally overconstraining what optimizations an implementation is allowed to do.  Perhaps /cc @gsathya though, maybe I am overthinking this.

**Comment by littledan** [comment]
Well, if you want to keep this text, we should clarify that finalizers are not run until the next *task*, not microtask.

**Comment by wingo** [comment]
Good point!  I changed a couple mentions of "microtask" to "task".

**Comment by littledan** [comment]
OK, this is a clear fix vs the previous text, but if folks have other ideas about how to present this information, please submit a follow-up PR.

**Pull request merged**
