### PR TITLE
WIP: Allow not yielding empty cells

### PR DESCRIPTION
**Pull request by mhofman**
Based on @littledan's invariant from #167

Operational steps scheduling `HostCleanupFinalizationGroup` when the iterator ends early.

### CODE REVIEW

**Comment by littledan** [comment]
When is [[Interrupted]] ever set to true?

**Comment by mhofman** [comment]
I wrote this quickly (and I guess backwards) to show what the behavior of an interrupting implementation should be. The idea was that when/if the implementation wants to interrupt the program's iteration it can set  [[Interrupted]] to true.

I need to rewrite it to something like:
```
1. If _iterator_.[[Used]] is *true*, then an implementation may perform the following steps,
    1. Set _iterator_.[[Interrupted]] to *true*
    1. Return CreateIterResultObject(*undefined*, *true*).
```

**Comment by mhofman** [comment]
I rebased this PR on top of the first 2 commits of #167 to show what operational steps scheduling CleanupFinalizationGroup would look like.

**Comment by littledan** [comment]
I don't think the workings need to be made any more explicit than they are. And in particular, I doubt the host's involvement here, beyond the existing hook for scheduling the finalizer callback. So I'm closing this PR for now, but I'd welcome continued editorial refinements to this specification.

**Pull request closed without merging**
