### PR TITLE
Clarify that holdings should not refer to the weak target

### PR DESCRIPTION
**Pull request by mathiasbynens**
Suggested by @ulan. PTAL

### CODE REVIEW

**Comment by leobalter** [comment]
So this needs to be done in here: https://tc39.es/proposal-weakrefs/#sec-finalization-group.prototype.register

Currently `FinalizationGroup#register` allows holdings to be the same object as target

**Comment by mhofman** [comment]
@leobalter, I don't think it needs to be in the spec.
A check in register can only be partial and prevent the target itself from being used, not an object which holds a reference to it.

**Comment by leobalter** [comment]
After the step 3 there should be a check, within the following examples:

```
n. If Type(holdings) is Object, then
  a. If target and holdings are the same Object value, throw a TypeError exception.
```

or reusing current abstractions:

```
n. If SameValue(target, holdings) is true, throw a TypeError exception.
```

**Comment by leobalter** [comment]
> @leobalter, I don't think it needs to be in the spec.
> A check in register can only be partial and prevent the target itself from being used, not an object which holds a reference to it.

It needs to be in the spec, otherwise I can't validate this. Per spec, we currently have tests that assert target and holdings can be the same value.

---

Maybe this is rather a recommendation only than a norm? If so, the readme file works just well, and we can't prevent this non-productive register from happening.

**Comment by mhofman** [comment]
It's a recommendation. A target object referenced by a holding value effectively has its identity observable in a future execution, so that makes it non collectible.

I actually thought I had added this clarification in the explainer before, but looks like I forgot.

**Comment by ljharb** [comment]
Certainly it seems like a good thing to error if target === holdings, but if holdings is a function that closes over target, say, there’s not really a good way to prevent that normatively (or to test for it) - which is why that part makes sense for an explainer?

**Comment by mathiasbynens** [comment]
+1 This does not necessarily need to be part of the spec. That's why I used "should" (RFC2119) and not "must" in this PR.

**Comment by gsathya** [comment]
LGTM.

Do we additionally want to change the spec to throw if `target === holdings`?

@erights

**Comment by erights** [comment]
> Do we additionally want to change the spec to throw if `target === holdings`?

@gsathya Good question! I think so. 

OTOH, it would only be a heuristic bug catcher, rather than providing any actual safety property. It would not detect, for example, when holdings is `[target]`. This kind of heuristic bug catcher, when made an error case, sometimes just leads to conditionals to avoid triggering the error, still without producing any actual safety property.

Nevertheless, still, I think so.

Attn @dtribble

**Pull request merged**
