### PR TITLE
Normative: rename deref to get

### PR DESCRIPTION
**Pull request by littledan**
Suggestion from Kenneth Christiansen
https://github.com/w3ctag/design-reviews/issues/321#issuecomment-494461104

### CODE REVIEW

**Comment by erights** [comment]
Reject this PR. We started with `get` and renamed to `deref` on purpose.

Attn @dtribble

**Comment by littledan** [comment]
@erights I missed this discussion. What was the rationale?

**Comment by syg** [comment]
I don't recall the original discussion, but I also dislike "get". I think it's too general a term for a very specific concept that'll come up often in discussion, both written and spoken. Imagine a hypothetical convo of explaining WeakRef semantics to someone unfamiliar:

Alice: A gotten WeakRef is guaranteed for the turn of the event loop.
Bob: Gotten from where?
Alice: I mean a WeakRef that had "get" called on it.

**Comment by littledan** [comment]
cc @kenchris

**Comment by littledan** [comment]
OK, given the hesitation here from @erights, @gsathya and @syg, let's conclude that we're not making this name change.

**Pull request closed without merging**
