### PR TITLE
Fix a bug in the `IterableWeakMap` example

### PR DESCRIPTION
**Pull request by isiahmeadows**

### CODE REVIEW

**Comment by ljharb** [comment]
In master, it’s registered with the key, and unregistered with the weakref. This PR seems to fix it to unregister with the key.

**Comment by littledan** [comment]
It looks to me like it's registered with the WeakRef as the unregister token.

**Comment by ljharb** [comment]
The first argument in register [here](https://github.com/tc39/proposal-weakrefs/blob/master/README.md#iterable-weakmaps) is `key`; can you help me understand what I’m missing?

**Comment by littledan** [comment]
The unregisterToken is the third argument, not the first. See https://tc39.es/proposal-weakrefs/#sec-finalization-group.prototype.register .

**Comment by ljharb** [comment]
Thanks, that clears it up. Seems like the PR is incorrect then.

**Comment by isiahmeadows** [comment]
Oh okay. Thanks, didn't quite catch that!

**Pull request closed without merging**
